//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.03 at 03:56:46 PM EEST 
//


package org.dg.iati.api.jaxb.iatiApiMapping;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dg.iati.api.jaxb.iatiApiMapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GlobalQuery_QNAME = new QName("", "global-query");
    private final static QName _Content_QNAME = new QName("", "content");
    private final static QName _Query_QNAME = new QName("", "query");
    private final static QName _IatiActivity_QNAME = new QName("", "iati-activity");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _Attribute_QNAME = new QName("", "attribute");
    private final static QName _GeneratedDatetime_QNAME = new QName("", "generated-datetime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dg.iati.api.jaxb.iatiApiMapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IatiApiMapping }
     * 
     */
    public IatiApiMapping createIatiApiMapping() {
        return new IatiApiMapping();
    }

    /**
     * Create an instance of {@link GlobalSettings }
     * 
     */
    public GlobalSettings createGlobalSettings() {
        return new GlobalSettings();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link Datasource }
     * 
     */
    public Datasource createDatasource() {
        return new Datasource();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link RefType }
     * 
     */
    public RefType createRefType() {
        return new RefType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "global-query")
    public JAXBElement<TypeType> createGlobalQuery(TypeType value) {
        return new JAXBElement<TypeType>(_GlobalQuery_QNAME, TypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content")
    public JAXBElement<ContentType> createContent(ContentType value) {
        return new JAXBElement<ContentType>(_Content_QNAME, ContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "query")
    public JAXBElement<QueryType> createQuery(QueryType value) {
        return new JAXBElement<QueryType>(_Query_QNAME, QueryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iati-activity")
    public JAXBElement<TypeType> createIatiActivity(TypeType value) {
        return new JAXBElement<TypeType>(_IatiActivity_QNAME, TypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attribute")
    public JAXBElement<AttributeType> createAttribute(AttributeType value) {
        return new JAXBElement<AttributeType>(_Attribute_QNAME, AttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "generated-datetime")
    public JAXBElement<TypeType> createGeneratedDatetime(TypeType value) {
        return new JAXBElement<TypeType>(_GeneratedDatetime_QNAME, TypeType.class, null, value);
    }

}
